language: node_js
node_js:
  - node

cache: yarn

before_script:
  - yarn typecheck
  - yarn lint

after_script:
  - yarn coverage

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  local_dir: dist/
  # on:
  #   branch: master
